### PR TITLE
Test core object

### PR DESCRIPTION
**Pull request by kevin-kariuki**
@kspurgin Some fields have carets which I ended up trying to use from the comments you hared for core-media and core-exhibition.

### CODE REVIEW

**Comment by kspurgin** [comment]
@kevin-kariuki -- I'm seeing this kind of thing in the "Resolve conflicts":

```
<<<<<<< core-object
    context 'collectionobject record' do
      before(:all) do
        @loanoutmapper = get_json_record_mapper(path: 'spec/fixtures/files/mappers/release_6_1/core/core_6_1_0-collectionobject.json')
        @handler = DataHandler.new(record_mapper: @loanoutmapper, cache: @cache, client: core_client, config: @config)
=======
    context 'media record' do
      before(:all) do
        @movementmapper = get_json_record_mapper(path: 'spec/fixtures/files/mappers/release_6_1/core/core_6_1_0-media.json')
        @handler = DataHandler.new(record_mapper: @movementmapper, cache: @cache, client: core_client, config: @config)
>>>>>>> master
```

I think that the following seem to help git deal with these files without conflicts (or at least with less CONFUSING conflicts!: 

A) making sure you are using correct recordtype specific variable names (i.e. don't have `@loanoutmapper` in the collectionobject test or `@movementmapper` in the media test)

B) putting the record type tests in alphabetical order in the file instead of adding to the end

**Comment by kevin-kariuki** [comment]
Okay, will keep this in mind for the next work I will be doing.

**Comment by kspurgin** [comment]
Are you still working on this one or was it waiting for me to review?

**Comment by kevin-kariuki** [comment]
As we discussed on the call yesterday you were to review this one.

**Review by kspurgin — APPROVED** [review]

**Pull request merged**
